# Dependencies
markdown:         redcarpet
highlighter:      pygments
plugins:          ["jekyll-paginate", "redcarpet", "jekyll-gist", "pygments.rb"]

# Permalinks
permalink:        pretty

# Setup
title:            Xavier
tagline:          'Cloud'
description:      '<a href="https://github.com/marcusrafael" target="_blank">@marcusrafael</a>'
url:              https://marcusrafael.github.io
baseurl:          https://marcusrafael.github.io/marcusrafael.github.io/

author:
  name:           'Xavier'
  url:            https://marcusrafael.github.io

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/marcusrafael/marcusrafael.github.io
